### ISSUE TITLE
房屋查询报错

### ISSUE THREAD

**Issue by RobertYz** [aaron-lii/TataruBot2#11]
![image](https://github.com/aaron-lii/TataruBot2/assets/126949481/372e0807-22d7-4c79-a84d-90cb9d8c203c)

**Comment by aaron-lii** [comment]
> ![image](https://user-images.githubusercontent.com/126949481/242559535-372e0807-22d7-4c79-a84d-90cb9d8c203c.png)

@RobertYz 更新一下插件，再试试看有没有报错

**Comment by RobertYz** [comment]
房子可以查了

**Comment by RobertYz** [comment]
> > ![image](https://user-images.githubusercontent.com/126949481/242559535-372e0807-22d7-4c79-a84d-90cb9d8c203c.png)
> 
> @RobertYz 更新一下插件，再试试看有没有报错

更新之后可以查房子了
