### ISSUE TITLE
塔塔露帮帮忙没有返回消息

### ISSUE THREAD

**Issue by RobertYz** [aaron-lii/TataruBot2#12]
发送塔塔露帮帮忙之后，没有返回所有功能的菜单列表消息

**Comment by aaron-lii** [comment]
@RobertYz 你是以插件方式安装使用的吗？试一下@你的机器人然后接帮帮忙，比如“@塔塔露一号帮帮忙”。可能是你机器人的.env文件里面给机器人设置了其他昵称或者没有设置昵称。

**Comment by aaron-lii** [comment]
看看你使用的是.env.prod还是.env.dev，把里面对应的 NICKNAME=["塔塔露"]  设置一个昵称，比如设置“塔塔露”就可以“塔塔露帮帮忙”，设置“张三”就可以“张三帮帮忙”

**Comment by RobertYz** [comment]
> 看看你使用的是.env.prod还是.env.dev，把里面对应的 NICKNAME=["塔塔露"] 设置一个昵称，比如设置“塔塔露”就可以“塔塔露帮帮忙”，设置“张三”就可以“张三帮帮忙”

谢谢，可以了，在配置文件里加上了昵称
