### ISSUE TITLE
请问这机器人可以查询logs吗

### ISSUE THREAD

**Issue by strongerzzx** [aaron-lii/TataruBot2#2]
请问这机器人支持该功能吗

**Comment by aaron-lii** [comment]
> 请问这机器人支持该功能吗

你是要查某个boss对应职业的dps分段吗？还是查哪种数据？

**Comment by strongerzzx** [comment]
嗯，dps分段。 比如我想查镰刀在某个boss中 logs20 logs30 logs90这样的输出量



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月20日(星期二) 下午2:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aaron-lii/TataruBot2] 请问这机器人可以查询logs吗 (Issue #2)





  
请问这机器人支持该功能吗
  
你是要查某个boss对应职业的dps分段吗？还是查哪种数据？

**Comment by aaron-lii** [comment]
> 嗯，dps分段。 比如我想查镰刀在某个boss中 logs20 logs30 logs90这样的输出量
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年12月20日(星期二) 下午2:33 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [aaron-lii/TataruBot2] 请问这机器人可以查询logs吗 (Issue #2) 请问这机器人支持该功能吗 你是要查某个boss对应职业的dps分段吗？还是查哪种数据？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

@strongerzzx 行 应该可以  我晚点更新一下

**Comment by strongerzzx** [comment]
请问&nbsp; 适配6.2版本的零式吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月20日(星期二) 下午2:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aaron-lii/TataruBot2] 请问这机器人可以查询logs吗 (Issue #2)





  
嗯，dps分段。 比如我想查镰刀在某个boss中 logs20 logs30 logs90这样的输出量
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年12月20日(星期二) 下午2:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [aaron-lii/TataruBot2] 请问这机器人可以查询logs吗 (Issue #2) 请问这机器人支持该功能吗 你是要查某个boss对应职业的dps分段吗？还是查哪种数据？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
@strongerzzx 行 应该可以  我晚点更新一下

**Comment by aaron-lii** [comment]
> 请问&nbsp; 适配6.2版本的零式吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年12月20日(星期二) 下午2:37 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [aaron-lii/TataruBot2] 请问这机器人可以查询logs吗 (Issue #2) 嗯，dps分段。 比如我想查镰刀在某个boss中 logs20 logs30 logs90这样的输出量 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年12月20日(星期二) 下午2:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [aaron-lii/TataruBot2] 请问这机器人可以查询logs吗 (Issue #2) 请问这机器人支持该功能吗 你是要查某个boss对应职业的dps分段吗？还是查哪种数据？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; @strongerzzx 行 应该可以 我晚点更新一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

@strongerzzx 最近有点忙，争取能支持吧

**Comment by aaron-lii** [comment]
logs查询功能更新上了，有新版本零式，如果有什么使用问题再看看吧
