### ISSUE TITLE
物品查询异常了

### ISSUE THREAD

**Issue by LingluoYusa** [aaron-lii/TataruBot2#4]
搜索 物品 南瓜浓汤
在聊天栏里回复的是 搜索失败！JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
新价格和价格两个关键字都试过了，回复都一样的

**Comment by aaron-lii** [comment]
@LingluoYusa 修复了，可以更新看一下有没有问题

**Comment by LingluoYusa** [comment]
感谢，可以使用了
