### ISSUE TITLE
有没有插件版的 不想删掉自己的机器人 T.T

### ISSUE THREAD

**Issue by Annnnh1010** [aaron-lii/TataruBot2#5]

**Comment by aaron-lii** [comment]
@Annnnh1010 你指的是nonebot的插件吗？

**Comment by Annnnh1010** [comment]
啊对

**Comment by aaron-lii** [comment]
@Annnnh1010 我研究一下

**Comment by Annnnh1010** [comment]
啊哈 已经用你的机器人 然后把自己用的插件装上啦

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aaron-lii** [comment]
更新了作为插件的使用方法，https://github.com/aaron-lii/TataruBot2/blob/main/README_PIP.md，如果遇到新的问题再看看

**Comment by KotoriTaiho** [comment]
按文档要求如果设置为内置插件加载时提示找不到插件
![395723c9c4deb78ef9978ae2110cb650](https://github.com/aaron-lii/TataruBot2/assets/53947653/74cb6160-a80a-48da-b82e-c007902bfcc8)
如果像其他插件一样加载则能正常加载，但是不会对命令有响应
![c484bdb2747efdb2cfc07f4a2b1cfc6d](https://github.com/aaron-lii/TataruBot2/assets/53947653/74b27987-a823-4f2a-90d8-f129622e48b8)
配置文件信息
![image](https://github.com/aaron-lii/TataruBot2/assets/53947653/61bdc654-3136-4697-a566-c30d10d5298c)
