### ISSUE TITLE
似乎房屋查询插件的协程出现了问题？

### ISSUE THREAD

**Issue by Moekey114514** [aaron-lii/TataruBot2#7]
![image](https://github.com/aaron-lii/TataruBot2/assets/48763754/ba6215d8-ef6c-454e-9706-c7f3bbfa36e5)
问题如图，以前是不能使用房屋查询功能，现在直接无法在nonebot里面导入了

**Comment by aaron-lii** [comment]
@Moekey114514 更新了代码了，应该可以用了

**Comment by Moekey114514** [comment]
![image](https://github.com/aaron-lii/TataruBot2/assets/48763754/9b492137-6dd7-45af-a38f-cd0f98ddda67)

不太确定，用了0.1.15好像还是没法导入

**Comment by aaron-lii** [comment]
> ![image](https://user-images.githubusercontent.com/48763754/239824955-9b492137-6dd7-45af-a38f-cd0f98ddda67.png)
> 
> 不太确定，用了0.1.15好像还是没法导入

哦，你把nonebot目录下的之前版本的配置文件tatarubot2_conf.json删了，然后再重启一下机器人，让他自动生成一下配置文件再试试。

**Comment by Moekey114514** [comment]
原来是这样！完全修复了，感谢
