### ISSUE TITLE
大大咨询一下查价的问题。

### ISSUE THREAD

**Issue by babytotdd** [aaron-lii/TataruBot2#8]
![image](https://github.com/aaron-lii/TataruBot2/assets/36141861/4723d32b-d5cd-43fe-8c42-12e3afcbf293)

go-cphttp v1.0.1  . Mrs4s

Universalis.app/api：
正常，浏览器可以访问返回JSON；

异常问题：
消息发出后，可以返回消息，PC客户端状态中也能看到有新消息；但是在群内无法显示内容，PC客户端能显示接收到信息，但是信息内为空，且没有返回内容；

xkl.

**Comment by aaron-lii** [comment]
@babytotdd 如果universails能正常连接的话，可能是消息被qq吞了，最近查物价的信息被qq吞的有点厉害。等我更新一下再看看log

**Comment by aaron-lii** [comment]
@babytotdd 更新一下代码，删除旧的tatarubot_conf.json，再试一下查物价看看是什么情况

**Comment by babytotdd** [comment]
@aaron-lii 

> @babytotdd 更新一下代码，删除旧的tatarubot_conf.json，再试一下查物价看看是什么情况

新Clone 下来的项目 启动后 报告plugins 无法import； 麻烦大大看下。
![image](https://github.com/aaron-lii/TataruBot2/assets/36141861/651b981b-aef4-4f57-9e15-5a4b290a48e4)

**Comment by babytotdd** [comment]
> @aaron-lii
> 
> > @babytotdd 更新一下代码，删除旧的tatarubot_conf.json，再试一下查物价看看是什么情况
> 
> 新Clone 下来的项目 启动后 报告plugins 无法import； 麻烦大大看下。 ![image](https://user-images.githubusercontent.com/36141861/239720609-651b981b-aef4-4f57-9e15-5a4b290a48e4.png)

然后是程序连接后，发送的内容没有响应回复。

**Comment by aaron-lii** [comment]
> > @aaron-lii
> > > @babytotdd 更新一下代码，删除旧的tatarubot_conf.json，再试一下查物价看看是什么情况
> > 
> > 
> > 新Clone 下来的项目 启动后 报告plugins 无法import； 麻烦大大看下。 ![image](https://user-images.githubusercontent.com/36141861/239720609-651b981b-aef4-4f57-9e15-5a4b290a48e4.png)
> 
> 然后是程序连接后，发送的内容没有响应回复。

往下拉一拉看看是我代码里哪部分报错了。有新加的依赖你看看装了没有。pip install -r requirements.txt

**Comment by babytotdd** [comment]
@aaron-lii 感谢大大处理！
